{% set name = "warp-lang" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/warp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2186eaa963868642f965bd787bd881cd6c0e3caabc44811af8f9dd1cb3ae2f93
  patches:
    - 01-find_g++_env.patch
    - 02-add_macro_def_build.patch
    - 03-install_deps_llvm_conda.patch

build:
  script:
    - {{ PYTHON }} build_lib.py
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-cache-dir
  number: 0
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - gitpython
    - numpy
  run:
    - python

test:
  imports:
    - warp
  commands:
    - pip check
    # Python tests require CUDA 11.5
    # - {{ PYTHON }} -m warp.test
  requires:
    - pip
    - pytest

about:
  home: https://github.com/NVIDIA/warp
  summary: 'A Python framework for high-performance simulation and graphics programming.'
  license: LicenseRef-NVIDIA-Software-License-warp
  license_file:
    - copyright.py
    - LICENSE.md
    - warp/native/cutlass/LICENSE.txt
    - licenses/llvm-LICENSE.txt

extra:
  recipe-maintainers:
    - flferretti
    - traversaro
